#!/usr/bin/env bash
# Feature #18a shipping script — run from the repo root
# Generated by shipper agent 2026-05-11
# DO NOT run with --no-verify on any step.
set -euo pipefail

REPO="/Users/nousunio/Repos/Learnings/claude-code/druum"
BRANCH="feature/18a-town-square-shop-inn"

cd "$REPO"

echo "=== Step 1: Create GitButler branch ==="
but branch new "$BRANCH"

echo "=== Step 2a: Stage CODE files to the branch ==="
# Stage all the new/modified source, plugin, and asset files for Commit 1
but stage src/data/town.rs "$BRANCH"
but stage src/data/mod.rs "$BRANCH"
but stage src/plugins/loading/mod.rs "$BRANCH"
but stage src/plugins/town/gold.rs "$BRANCH"
but stage src/plugins/town/inn.rs "$BRANCH"
but stage src/plugins/town/placeholder.rs "$BRANCH"
but stage src/plugins/town/shop.rs "$BRANCH"
but stage src/plugins/town/square.rs "$BRANCH"
but stage src/plugins/town/mod.rs "$BRANCH"
but stage assets/town/shop_stock.ron "$BRANCH"
but stage assets/town/recruit_pool.ron "$BRANCH"
but stage assets/town/town_services.ron "$BRANCH"

echo "=== Step 3a: Commit 1 — feat(town): ==="
but commit --message-file project/shipper/feature-18a-commit1-msg.txt

echo "=== Step 2b: Stage DOCS files to the branch ==="
but stage project/research/20260511-feature-18-town-hub-and-services.md "$BRANCH"
but stage project/plans/20260511-180000-feature-18a-town-square-shop-inn.md "$BRANCH"
but stage project/implemented/20260511-180000-feature-18a-town-square-shop-inn.md "$BRANCH"
but stage project/implemented/20260511-190000-feature-18a-town-square-shop-inn.md "$BRANCH"
but stage project/orchestrator/PIPELINE-STATE.md "$BRANCH"

echo "=== Step 3b: Commit 2 — docs: ==="
but commit --message-file project/shipper/feature-18a-commit2-msg.txt

echo "=== Step 4: Push branch (runs pre-push hooks) ==="
but push -u origin "$BRANCH"

echo "=== Step 5: Open PR ==="
gh pr create \
  --title "feat(town): add Town Square, Shop, and Inn screens (#18a)" \
  --base main \
  --head "$BRANCH" \
  --body-file project/shipper/feature-18a-pr-body.md

echo "=== Done ==="
gh pr view --web
